# Generated by Django 5.2.7 on 2025-11-03 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0003_eventtype_clientfile_scheduleevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='notefield',
            name='choices',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='note',
            name='therapist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='therapy.therapistprofile'),
        ),
        migrations.AlterField(
            model_name='notefield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('number', 'Number'), ('date', 'Date'), ('choice', 'Multiple Choice')], max_length=50),
        ),
    ]
