# Generated by Django 5.2.7 on 2025-11-06 10:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0004_notefield_choices_alter_note_therapist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notefield',
            name='choices',
        ),
        migrations.AddField(
            model_name='note',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='note',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('final', 'Final')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='note',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='notefield',
            name='options',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='notefield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('number', 'Number'), ('date', 'Date'), ('choice', 'Multiple Choice'), ('checkboxes', 'Checkbox Group'), ('select', 'Dropdown'), ('likert', 'Likert Scale')], max_length=50),
        ),
    ]
