# Generated by Django 5.2.7 on 2025-11-07 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0005_remove_notefield_choices_note_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='cosign_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='cosigned_by',
            field=models.ManyToManyField(blank=True, help_text='Therapists who have completed co-signing this note.', related_name='cosigned_notes', to='therapy.therapistprofile'),
        ),
        migrations.AddField(
            model_name='note',
            name='cosigners',
            field=models.ManyToManyField(blank=True, help_text='Therapists selected to co-sign this note.', related_name='cosign_notes', to='therapy.therapistprofile'),
        ),
        migrations.AddField(
            model_name='note',
            name='require_cosign',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_cosign', 'Pending Co-Sign'), ('final', 'Final')], default='draft', max_length=20),
        ),
    ]
