# Generated by Django 5.2.7 on 2026-02-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0006_note_cosign_completed_note_cosigned_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='waitlisted',
            field=models.BooleanField(default=False),
        ),
    ]
