# Generated by Django 5.2.10 on 2026-02-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0007_clientprofile_waitlisted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='waitlisted',
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='address_line3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='appointment_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='civil_id_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='concession_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='extra_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='followup_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='followup_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='gender_identity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='invoice_email_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='invoice_extra_information',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='invoice_to',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='marketing_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='marketing_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='medicare_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='patient_file_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='phone_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='post_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='preferred_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='privacy_policy_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='pronouns',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='receive_booking_cancellation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='receive_booking_confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='referral_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='referring_doctor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='related_patients',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='reminder_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='reminder_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='sex',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='terminated_patient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='termination_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='termination_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='time_zone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
