# Generated by Django 5.2.10 on 2026-02-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0013_add_template_termination_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='notetemplate',
            name='sections',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
