# Generated by Django 5.2.7 on 2026-04-11 03:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0028_therapistapplycontent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('booking_request_created', 'Booking request created'), ('booking_request_confirmed', 'Booking request confirmed'), ('booking_request_declined', 'Booking request declined'), ('booking_request_cancelled', 'Booking request cancelled'), ('booking_request_expired', 'Booking request expired'), ('appointment_scheduled', 'Appointment scheduled'), ('appointment_cancelled', 'Appointment cancelled'), ('appointment_completed', 'Appointment completed'), ('appointment_rescheduled', 'Appointment rescheduled')], max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('related_model', models.CharField(help_text='Model name related to this notification (e.g., BookingRequest).', max_length=100)),
                ('related_id', models.CharField(help_text='Primary key or identifier of the related record.', max_length=64)),
                ('action_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['start_time', 'date']},
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No show'), ('rescheduled', 'Rescheduled')], default='scheduled', help_text='Current appointment status.', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='therapistscontent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(help_text='Start time of the slot.')),
                ('end_time', models.DateTimeField(help_text='End time of the slot.')),
                ('status', models.CharField(choices=[('open', 'Open'), ('held', 'Held'), ('blocked', 'Blocked'), ('booked', 'Booked'), ('expired', 'Expired')], default='open', help_text='Current status of this slot.', max_length=20)),
                ('visible_to_clients', models.BooleanField(default=True, help_text='If true, this slot can appear in the client booking interface.')),
                ('held_until', models.DateTimeField(blank=True, help_text='If held, the time until which this slot remains reserved.', null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes for therapist/admin use only.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('therapist', models.ForeignKey(help_text='Therapist who created this availability slot.', on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='therapy.therapistprofile')),
            ],
            options={
                'verbose_name': 'Availability slot',
                'verbose_name_plural': 'Availability slots',
                'ordering': ['start_time'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='availability_slot',
            field=models.ForeignKey(blank=True, help_text='Availability slot linked to this appointment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='therapy.availabilityslot'),
        ),
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Awaiting confirmation'), ('confirmed', 'Confirmed'), ('declined', 'Declined'), ('cancelled_by_client', 'Cancelled by client'), ('cancelled_by_therapist', 'Cancelled by therapist'), ('expired', 'Expired')], default='pending', help_text='Current status of this booking request.', max_length=25)),
                ('message_from_client', models.TextField(blank=True, help_text='Optional message from the client to the therapist.')),
                ('therapist_response_note', models.TextField(blank=True, help_text='Optional response note from the therapist.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('availability_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests', to='therapy.availabilityslot')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests', to='therapy.clientprofile')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests', to='therapy.therapistprofile')),
            ],
            options={
                'verbose_name': 'Booking request',
                'verbose_name_plural': 'Booking requests',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='booking_request',
            field=models.OneToOneField(blank=True, help_text='The booking request that created this appointment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment', to='therapy.bookingrequest'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['therapist', 'start_time', 'status'], name='therapy_app_therapi_a3e215_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['client', 'start_time', 'status'], name='therapy_app_client__ffe54a_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', 'start_time'], name='therapy_app_status_b94f5e_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time')), ('start_time__isnull', True), ('end_time__isnull', True), _connector='OR'), name='appointment_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['scheduled', 'rescheduled'])), fields=('availability_slot',), name='unique_active_appointment_per_slot'),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient_user_profile',
            field=models.ForeignKey(help_text='User who should receive this notification.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='availabilityslot',
            index=models.Index(fields=['therapist', 'start_time'], name='therapy_ava_therapi_e1703c_idx'),
        ),
        migrations.AddIndex(
            model_name='availabilityslot',
            index=models.Index(fields=['therapist', 'status', 'start_time'], name='therapy_ava_therapi_f4500e_idx'),
        ),
        migrations.AddIndex(
            model_name='availabilityslot',
            index=models.Index(fields=['status', 'visible_to_clients', 'start_time'], name='therapy_ava_status_e5cd39_idx'),
        ),
        migrations.AddConstraint(
            model_name='availabilityslot',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='availability_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='bookingrequest',
            index=models.Index(fields=['therapist', 'status', 'created_at'], name='therapy_boo_therapi_c8391d_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingrequest',
            index=models.Index(fields=['client', 'status', 'created_at'], name='therapy_boo_client__22724f_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingrequest',
            index=models.Index(fields=['availability_slot', 'status'], name='therapy_boo_availab_097a54_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingrequest',
            index=models.Index(fields=['status', 'created_at'], name='therapy_boo_status_69da8f_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookingrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'confirmed'])), fields=('availability_slot',), name='unique_active_request_per_slot'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient_user_profile', 'is_read', 'created_at'], name='therapy_not_recipie_52eb00_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type', 'created_at'], name='therapy_not_type_5561fb_idx'),
        ),
    ]
