# Generated by Django 5.2.7 on 2026-04-11 03:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0029_notification_alter_appointment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Auth user linked to this client profile.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Auth user linked to this therapist profile.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='therapist_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TherapeuticRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended')], default='active', help_text='Current relationship status.', max_length=20)),
                ('is_primary', models.BooleanField(default=False, help_text='Marks the primary therapist for this client.')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the relationship started.')),
                ('ended_at', models.DateTimeField(blank=True, help_text='When the relationship ended (if ended).', null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this relationship.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(help_text='Client in this relationship.', on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='therapy.clientprofile')),
                ('therapist', models.ForeignKey(help_text='Therapist in this relationship.', on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='therapy.therapistprofile')),
            ],
            options={
                'verbose_name': 'Therapeutic relationship',
                'verbose_name_plural': 'Therapeutic relationships',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['therapist', 'status', 'started_at'], name='therapy_the_therapi_5d8a8a_idx'), models.Index(fields=['client', 'status', 'started_at'], name='therapy_the_client__f19a52_idx'), models.Index(fields=['status', 'started_at'], name='therapy_the_status_9438fa_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('ended_at__gt', models.F('started_at')), ('ended_at__isnull', True), _connector='OR'), name='relationship_end_after_start'), models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('therapist', 'client'), name='unique_active_relationship_per_pair'), models.UniqueConstraint(condition=models.Q(('is_primary', True), ('status', 'active')), fields=('client',), name='unique_primary_therapist_per_client')],
            },
        ),
    ]
