# Generated by Django 5.2.7 on 2026-04-12 19:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0030_clientprofile_user_therapistprofile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('booking_request_created', 'Booking request created'), ('booking_request_confirmed', 'Booking request confirmed'), ('booking_request_declined', 'Booking request declined'), ('booking_request_cancelled', 'Booking request cancelled'), ('booking_request_expired', 'Booking request expired'), ('appointment_scheduled', 'Appointment scheduled'), ('appointment_cancelled', 'Appointment cancelled'), ('appointment_completed', 'Appointment completed'), ('appointment_rescheduled', 'Appointment rescheduled'), ('resource_assigned', 'Resource assigned')], max_length=40),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('resource_type', models.CharField(choices=[('file', 'File'), ('link', 'Link'), ('text', 'Text')], default='file', help_text='The primary content type for this resource.', max_length=20)),
                ('file', models.FileField(blank=True, help_text='Upload a file for file-based resources.', null=True, upload_to='resources/')),
                ('url', models.URLField(blank=True, help_text='External link for link-based resources.')),
                ('text_content', models.TextField(blank=True, help_text='Inline text content for text-based resources.')),
                ('is_active', models.BooleanField(default=True, help_text='If false, the resource is hidden from assignment lists.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('therapist', models.ForeignKey(help_text='Therapist who owns this resource.', on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='therapy.therapistprofile')),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SharedResourceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('therapist_note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('viewed', 'Viewed'), ('completed', 'Completed')], default='assigned', help_text='Progress status for the assigned resource.', max_length=20)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_assignments_made', to='therapy.therapistprofile')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_assignments', to='therapy.clientprofile')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='therapy.resource')),
                ('therapeutic_relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_assignments', to='therapy.therapeuticrelationship')),
            ],
            options={
                'verbose_name': 'Shared resource assignment',
                'verbose_name_plural': 'Shared resource assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['therapist', 'is_active', 'created_at'], name='therapy_res_therapi_444323_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['resource_type', 'created_at'], name='therapy_res_resourc_9ff5e7_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedresourceassignment',
            index=models.Index(fields=['assigned_by', 'status', 'assigned_at'], name='therapy_sha_assigne_28a850_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedresourceassignment',
            index=models.Index(fields=['assigned_to', 'status', 'assigned_at'], name='therapy_sha_assigne_1c53d9_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedresourceassignment',
            index=models.Index(fields=['therapeutic_relationship', 'status'], name='therapy_sha_therape_0cd7f6_idx'),
        ),
    ]
