# Generated by Django 5.2.7 on 2026-04-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0031_alter_notification_type_resource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_first_session_free',
            field=models.BooleanField(default=False, help_text='True if this appointment is a 30-min free session.'),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='is_first_session_free',
            field=models.BooleanField(default=False, help_text="Whether this booking request exercises the client's first 30-min free session."),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='business_hours',
            field=models.JSONField(blank=True, default=dict, help_text="Stores repeating availability. Example: {'1': [{'startTime': '09:00', 'endTime': '17:00'}]}"),
        ),
    ]
