# Generated by Django 5.2.7 on 2026-04-14 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0032_appointment_is_first_session_free_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='therapist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='therapy.therapistprofile'),
        ),
    ]
