# Generated by Django 5.2.7 on 2026-04-14 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0033_alter_clientprofile_therapist'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='profile_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='specialties',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
