# Generated by Django 5.2.7 on 2026-04-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0034_therapistprofile_bio_therapistprofile_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistapplication',
            name='expertise_areas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='therapistapplication',
            name='highest_qualification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='therapistapplication',
            name='supervised_years',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='therapistapplication',
            name='supervisor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='therapistapplication',
            name='therapeutic_approach',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapistapplication',
            name='whatsapp_community',
            field=models.BooleanField(default=False),
        ),
    ]
