# Generated by Django 5.2.7 on 2026-04-16 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0035_therapistapplication_expertise_areas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistapplication',
            name='has_licenses',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='therapistapplication',
            name='interested_in_spaces',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='therapistapplication',
            name='whatsapp_community',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
