# Generated by Django 5.2.7 on 2026-04-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0036_therapistapplication_has_licenses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistprofile',
            name='affiliations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='concerns',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='is_queer_affirmative',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='modalities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='religion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='session_duration',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='years_experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
