# Generated by Django 5.2.7 on 2026-04-16 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0037_therapistprofile_affiliations_therapistprofile_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapistScreening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.JSONField(blank=True, default=dict)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('session_type_pref', models.CharField(blank=True, max_length=100, null=True)),
                ('service_type', models.CharField(blank=True, max_length=100, null=True)),
                ('therapist_gender_pref', models.CharField(blank=True, max_length=100, null=True)),
                ('therapy_style_pref', models.CharField(blank=True, max_length=100, null=True)),
                ('urgency', models.CharField(blank=True, max_length=100, null=True)),
                ('presenting_concerns', models.JSONField(blank=True, default=list)),
                ('primary_concern', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('impairment_level', models.CharField(blank=True, max_length=100, null=True)),
                ('prior_therapy', models.CharField(blank=True, max_length=100, null=True)),
                ('psychiatry_history', models.CharField(blank=True, max_length=100, null=True)),
                ('on_medication', models.CharField(blank=True, max_length=100, null=True)),
                ('has_diagnosis', models.CharField(blank=True, max_length=100, null=True)),
                ('diagnosis_details', models.TextField(blank=True, null=True)),
                ('health_factors', models.TextField(blank=True, null=True)),
                ('daily_functioning', models.CharField(blank=True, max_length=100, null=True)),
                ('sleep_quality', models.CharField(blank=True, max_length=100, null=True)),
                ('energy_level', models.CharField(blank=True, max_length=100, null=True)),
                ('appetite_level', models.CharField(blank=True, max_length=100, null=True)),
                ('support_level', models.CharField(blank=True, max_length=100, null=True)),
                ('support_sources', models.JSONField(blank=True, default=list)),
                ('suicidal_thoughts', models.CharField(blank=True, max_length=100, null=True)),
                ('past_self_harm', models.CharField(blank=True, max_length=100, null=True)),
                ('feels_safe', models.CharField(blank=True, max_length=100, null=True)),
                ('immediate_safety_concern', models.CharField(blank=True, max_length=100, null=True)),
                ('risk_level', models.CharField(default='routine', max_length=50)),
                ('dass_answers', models.JSONField(blank=True, default=dict)),
                ('dass_depression_score', models.IntegerField(blank=True, null=True)),
                ('dass_anxiety_score', models.IntegerField(blank=True, null=True)),
                ('dass_stress_score', models.IntegerField(blank=True, null=True)),
                ('dass_depression_level', models.CharField(blank=True, max_length=50, null=True)),
                ('dass_anxiety_level', models.CharField(blank=True, max_length=50, null=True)),
                ('dass_stress_level', models.CharField(blank=True, max_length=50, null=True)),
                ('summary_paragraph', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screenings', to='therapy.clientprofile')),
                ('recommended_therapists', models.ManyToManyField(blank=True, to='therapy.therapistprofile')),
            ],
        ),
    ]
