# Generated by Django 5.2.7 on 2026-04-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0038_therapistscreening'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistscreening',
            name='religion_pref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
