# Generated by Django 5.2.7 on 2026-04-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0039_therapistscreening_religion_pref'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistscreening',
            name='marketing_email_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='therapistscreening',
            name='marketing_whatsapp_consent',
            field=models.BooleanField(default=False),
        ),
    ]
