# Generated by Django 5.2.7 on 2026-04-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0040_therapistscreening_marketing_email_consent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistapplication',
            name='bachelors',
            field=models.FileField(blank=True, null=True, upload_to='therapist_applications/bachelors/'),
        ),
        migrations.AddField(
            model_name='therapistapplication',
            name='clinical_philosophy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapistapplication',
            name='email_updates',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='therapistapplication',
            name='license_doc',
            field=models.FileField(blank=True, null=True, upload_to='therapist_applications/licenses/'),
        ),
        migrations.AddField(
            model_name='therapistapplication',
            name='licenses_held',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapistapplication',
            name='masters',
            field=models.FileField(blank=True, null=True, upload_to='therapist_applications/masters/'),
        ),
        migrations.AddField(
            model_name='therapistapplication',
            name='supervisions_detailed',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='therapistapplication',
            name='therapeutic_stance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapistapplication',
            name='trainings_detailed',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='therapistapplication',
            name='treat_minors',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='therapistapplication',
            name='youngest_age',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
