# Generated by Django 5.2.7 on 2026-04-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0041_therapistapplication_bachelors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistapplication',
            name='additional_docs',
            field=models.FileField(blank=True, null=True, upload_to='therapist_applications/extra/'),
        ),
        migrations.AddField(
            model_name='therapistapplication',
            name='has_in_person_space',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='therapistapplication',
            name='has_private_online_space',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='therapistapplication',
            name='interested_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='therapistapplication',
            name='opt_in_spaces',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='therapistapplication',
            name='populations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='therapistapplication',
            name='relevant_experience',
            field=models.TextField(blank=True, null=True),
        ),
    ]
