# Generated by Django 5.2.7 on 2026-04-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0042_therapistapplication_additional_docs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistapplication',
            name='qualification_doc',
            field=models.FileField(blank=True, null=True, upload_to='therapist_applications/qualifications/'),
        ),
        migrations.AlterField(
            model_name='therapistapplication',
            name='linkedin',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
