# Generated by Django 5.2.7 on 2026-04-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0043_therapistapplication_qualification_doc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapistapplication',
            name='referral_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
