# Generated by Django 5.2.7 on 2026-04-17 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0045_contactmessage_quickbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning_signs', models.TextField(blank=True, help_text='How do I know when things are getting hard?')),
                ('coping_strategies', models.TextField(blank=True, help_text='Things I can do on my own')),
                ('social_distractions', models.TextField(blank=True, help_text='Places and people for distraction')),
                ('social_supports', models.TextField(blank=True, help_text='People I can ask for help')),
                ('professional_supports', models.TextField(blank=True, help_text='Professionals and agencies (MLC, Emergency)')),
                ('environment_safety', models.TextField(blank=True, help_text='How to make my environment safe')),
                ('reason_for_living', models.TextField(blank=True, help_text='One thing that is important to me')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='safety_plan', to='therapy.clientprofile')),
            ],
        ),
    ]
