# Generated by Django 5.2.7 on 2026-04-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0046_safetyplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientjournal',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='clientjournal',
            name='updates',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
