# Generated by Django 5.2.7 on 2026-04-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0047_clientjournal_extra_data_clientjournal_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientgoal',
            name='category',
            field=models.CharField(choices=[('daily', 'Daily'), ('short_term', 'Short Term'), ('long_term', 'Long Term')], default='short_term', max_length=20),
        ),
        migrations.AddField(
            model_name='clientgoal',
            name='color',
            field=models.CharField(default='#56756D', max_length=20),
        ),
        migrations.AddField(
            model_name='clientgoal',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
