# Generated by Django 5.2.7 on 2026-04-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0048_clientgoal_category_clientgoal_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('booking_request_created', 'Booking request created'), ('booking_request_confirmed', 'Booking request confirmed'), ('booking_request_declined', 'Booking request declined'), ('booking_request_cancelled', 'Booking request cancelled'), ('booking_request_expired', 'Booking request expired'), ('appointment_scheduled', 'Appointment scheduled'), ('appointment_cancelled', 'Appointment cancelled'), ('appointment_completed', 'Appointment completed'), ('appointment_rescheduled', 'Appointment rescheduled'), ('resource_assigned', 'Resource assigned'), ('streak_reminder', 'Streak reminder')], max_length=40),
        ),
    ]
