# Generated by Django 5.2.7 on 2026-04-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0049_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='default_duration',
            field=models.PositiveIntegerField(default=50, help_text='Default duration in minutes'),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='default_notes',
            field=models.TextField(blank=True, help_text='Pre-filled notes for this type', null=True),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='is_paid',
            field=models.BooleanField(default=True, help_text='Whether this event type is billable'),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='notify_therapist',
            field=models.BooleanField(default=False, help_text='Send email/notif when scheduled'),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='requires_client',
            field=models.BooleanField(default=True, help_text='Whether a patient must be linked'),
        ),
    ]
