# Generated by Django 5.2.7 on 2026-04-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0050_eventtype_default_duration_eventtype_default_notes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventtype',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='eventtype',
            name='group',
            field=models.CharField(blank=True, default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
