# Generated by Django 5.2.7 on 2026-04-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0051_alter_eventtype_options_eventtype_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='dass_scores',
            field=models.JSONField(blank=True, default=dict, help_text='DASS-21 scores and interpretations from the screening form.', null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='intake_clinical_notes',
            field=models.JSONField(blank=True, default=dict, help_text='Structured clinical intake data from the screening form, visible to the assigned therapist.', null=True),
        ),
    ]
