# Generated by Django 5.2.7 on 2026-04-21 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0052_clientprofile_dass_scores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='meeting_link',
            field=models.URLField(blank=True, help_text='Secure Jitsi/JaaS room URL for this session.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='is_supervisor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='supervision_bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='supervision_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('approved', 'Approved')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='supervision_years_experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
