# Generated by Django 5.2.7 on 2026-04-21 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0053_appointment_meeting_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistprofile',
            name='has_physical_space',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='physical_space_images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='physical_space_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='physical_space_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='supervision_areas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='supervision_modalities',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
