# Generated by Django 5.2.7 on 2026-04-21 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0054_therapistprofile_has_physical_space_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilityslot',
            name='visible_to_supervisees',
            field=models.BooleanField(default=True, help_text='If true, this slot can appear in the supervisor discovery interface.'),
        ),
    ]
