# Generated by Django 5.2.7 on 2026-04-21 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0055_availabilityslot_visible_to_supervisees'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisoryRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('terminated', 'Terminated')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supervisee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='being_supervised_relationships', to='therapy.therapistprofile')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervising_relationships', to='therapy.therapistprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SupervisionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('is_private', models.BooleanField(default=True, help_text='Always True - only visible to supervisor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='therapy.appointment')),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='therapy.supervisoryrelationship')),
            ],
        ),
        migrations.AddConstraint(
            model_name='supervisoryrelationship',
            constraint=models.UniqueConstraint(fields=('supervisor', 'supervisee'), name='unique_supervision_link'),
        ),
    ]
