# Generated by Django 5.2.7 on 2026-04-21 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0056_supervisoryrelationship_supervisionnote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='appointment',
            field=models.ForeignKey(blank=True, help_text='Link this note to a specific calendar event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_notes', to='therapy.appointment'),
        ),
        migrations.AddField(
            model_name='notetemplate',
            name='event_type',
            field=models.ForeignKey(blank=True, help_text='Link this template to a specific appointment type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='therapy.eventtype'),
        ),
    ]
