# Generated by Django 5.2.7 on 2026-04-22 02:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0057_note_appointment_notetemplate_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RazorpayPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(help_text='Amount in the smallest currency unit (e.g. paise).')),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('failed', 'Failed')], default='created', max_length=20)),
                ('razorpay_order_id', models.CharField(blank=True, default='', max_length=64)),
                ('razorpay_payment_id', models.CharField(blank=True, default='', max_length=64)),
                ('razorpay_signature', models.CharField(blank=True, default='', max_length=256)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='razorpay_payment', to='therapy.bookingrequest')),
            ],
        ),
    ]
