# Generated by Django 5.2.7 on 2026-04-22 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0058_razorpay_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistprofile',
            name='supervision_hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='SupervisionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='The first day of the month this report covers.')),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('total_minutes', models.PositiveIntegerField(default=0)),
                ('total_payable', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized'), ('invoiced', 'Invoiced'), ('paid', 'Paid')], default='draft', max_length=20)),
                ('report_data', models.JSONField(blank=True, default=dict, help_text='Detailed session breakdown and notes.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='therapy.supervisoryrelationship')),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('relationship', 'month')},
            },
        ),
    ]
