# Generated by Django 5.2.7 on 2026-04-24 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0064_therapistsubscriptioncharge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=255)),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('user_role', models.CharField(blank=True, max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('general', 'General Inquiry'), ('technical', 'Technical Issue / Bug'), ('billing', 'Billing & Subscription'), ('client-access', 'Client Access Issue'), ('resources', 'Resources / Tools'), ('other', 'Other')], default='general', max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='clientformassignment',
            new_name='therapy_cli_assigne_1db745_idx',
            old_name='therapy_clie_assigne_94f7c8_idx',
        ),
        migrations.RenameIndex(
            model_name='clientformassignment',
            new_name='therapy_cli_assigne_713442_idx',
            old_name='therapy_clie_assigne_625d2f_idx',
        ),
        migrations.RenameIndex(
            model_name='clientformassignment',
            new_name='therapy_cli_therape_73dae0_idx',
            old_name='therapy_clie_therape_d47ff4_idx',
        ),
        migrations.RenameIndex(
            model_name='therapistsubscriptioncharge',
            new_name='therapy_the_therapi_acd9b2_idx',
            old_name='therapy_ther_therapi_72f613_idx',
        ),
        migrations.RenameIndex(
            model_name='therapistsubscriptioncharge',
            new_name='therapy_the_razorpa_9ce5f6_idx',
            old_name='therapy_ther_razorpa_5ba718_idx',
        ),
        migrations.RenameIndex(
            model_name='therapistsubscriptioncharge',
            new_name='therapy_the_status_9fb623_idx',
            old_name='therapy_ther_status_f31cf0_idx',
        ),
        migrations.AddField(
            model_name='supportticket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
