# Generated by Django 5.2.7 on 2026-04-25 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0067_communitycategory_communitythread_communitycomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='community_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_resources', to='therapy.communitycategory'),
        ),
        migrations.AddField(
            model_name='resource',
            name='is_community',
            field=models.BooleanField(default=False, help_text='If true, this resource is shared with the entire Therapist Community.'),
        ),
        migrations.AddField(
            model_name='resource',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='resource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
