# Generated by Django 5.2.7 on 2026-04-25 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0068_resource_community_category_resource_is_community_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('client_phone', models.CharField(blank=True, max_length=20)),
                ('reason', models.TextField(help_text='Clinical reason for referral.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('is_internal_client', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internal_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='therapy.clientprofile')),
                ('receiving_therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_received', to='therapy.therapistprofile')),
                ('referring_therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_sent', to='therapy.therapistprofile')),
            ],
        ),
    ]
