# Generated by Django 5.2.7 on 2026-04-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0069_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistprofile',
            name='admin_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='clinical_judgment_answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='highest_qualification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='highest_qualification_proof',
            field=models.FileField(blank=True, null=True, upload_to='therapist_profile/qualification_proofs/'),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='is_initially_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='is_supervisor_licensed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='profile_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Pending Review'), ('changes_requested', 'Changes Requested'), ('awaiting_contract', 'Awaiting Contract'), ('approved', 'Approved (Live)')], db_index=True, default='draft', max_length=24),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='therapist_profile/resumes/'),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='supervisor_admin_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='therapistprofile',
            name='supervision_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Supervision Review'), ('awaiting_contract', 'Supervision Awaiting Contract'), ('approved', 'Licensed Supervisor')], default='none', max_length=20),
        ),
    ]
