# Generated by Django 5.2.7 on 2026-04-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0070_therapistprofile_admin_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistprofile',
            name='supervision_application_answers',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
