# Generated by Django 5.2.7 on 2026-04-25 19:34

from django.conf import settings
from django.db import migrations, models


def normalize_therapist_statuses_before_constraints(apps, schema_editor):
    TherapistProfile = apps.get_model("therapy", "TherapistProfile")

    # Normalize legacy literals that were used before the guarded enum states.
    TherapistProfile.objects.filter(profile_status="approved_live").update(profile_status="approved")
    TherapistProfile.objects.filter(supervision_status="licensed").update(supervision_status="approved")

    # Ensure supervision advanced states never exist on non-approved profiles.
    TherapistProfile.objects.filter(
        supervision_status__in=["awaiting_contract", "approved"]
    ).exclude(profile_status="approved").update(supervision_status="pending")


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0071_therapistprofile_supervision_application_answers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(normalize_therapist_statuses_before_constraints, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='therapistprofile',
            constraint=models.CheckConstraint(condition=models.Q(('profile_status__in', ['draft', 'submitted', 'changes_requested', 'awaiting_contract', 'approved'])), name='therapist_profile_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='therapistprofile',
            constraint=models.CheckConstraint(condition=models.Q(('supervision_status__in', ['none', 'pending', 'awaiting_contract', 'approved'])), name='therapist_supervision_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='therapistprofile',
            constraint=models.CheckConstraint(condition=models.Q(('supervision_status__in', ['none', 'pending']), ('profile_status', 'approved'), _connector='OR'), name='supervision_advanced_requires_profile_approved'),
        ),
    ]
