# Generated by Django 5.2.7 on 2026-04-27 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0072_therapistprofile_therapist_profile_status_valid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistprofile',
            name='contract_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='supervisor_contract_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PlatformFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('therapist', 'Therapist'), ('client', 'Client'), ('guest', 'Guest')], default='guest', max_length=20)),
                ('page_path', models.CharField(help_text='The URL/Path where the feedback was submitted.', max_length=255)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('ui_ux', 'UI/UX Improvement'), ('feature', 'New Feature Request'), ('clinical', 'Clinical Tool Improvement'), ('bug', 'Bug Report'), ('general', 'General Suggestion')], default='general', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('planned', 'Planned'), ('implemented', 'Implemented'), ('dismissed', 'Dismissed')], default='new', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Platform Feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
