# Generated by Django 5.2.7 on 2026-04-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0073_therapistprofile_contract_signed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notefield',
            name='field_key',
            field=models.CharField(blank=True, help_text='Stable identifier for this field', max_length=100, null=True),
        ),
    ]
